"use client";

import { FormEvent, useState } from "react";

type Language = "en" | "es" | "hi" | "zh" | "ar";
type Result = {
  location: { name: string; zip: string };
  aqi: 1 | 2 | 3 | 4 | 5;
  pollutants: { pm2_5?: number; pm10?: number; no2?: number; o3?: number };
  updatedAt: string;
  alerts: { id: string; event: string; headline: string; severity: string; instruction?: string | null }[];
};

const copy = {
  en: { name: "English", title: "Know your air. Protect your health.", subtitle: "Live air quality and official weather alerts for any U.S. ZIP code.", zip: "U.S. ZIP code", placeholder: "Enter ZIP code", check: "Check My Area", loading: "Checking…", error: "We couldn’t load that area. Check the ZIP code and try again.", scale: "OpenWeather AQI", updated: "Last updated", tips: "What you can do", alerts: "Weather alerts", clear: "No active weather alerts for this area.", levels: ["", "Good", "Fair", "Moderate", "Poor", "Very poor"], messages: ["", "The air is clean for most people.", "Air is generally acceptable. Sensitive people should pay attention to symptoms.", "Sensitive people may feel effects from the air.", "The air may affect everyone, especially sensitive groups.", "The air is unhealthy. Reduce exposure as much as possible."], safety: [[], ["Enjoy normal outdoor activities.", "Open windows if local conditions allow."], ["Sensitive people: take breaks during long outdoor activity.", "Keep rescue medication nearby if prescribed."], ["Sensitive people: shorten strenuous outdoor activity.", "Close windows if you smell smoke or feel symptoms.", "Consider a well-fitting mask outdoors."], ["Limit time and exercise outdoors.", "Keep windows closed and use an air filter if available.", "Wear a well-fitting mask when outside."], ["Stay indoors when possible.", "Run an air purifier or use a clean-air room.", "Follow local health and emergency guidance."]] },
  es: { name: "Español", title: "Conozca su aire. Proteja su salud.", subtitle: "Calidad del aire y alertas oficiales para cualquier código postal de EE. UU.", zip: "Código postal de EE. UU.", placeholder: "Ingrese el código postal", check: "Revisar mi zona", loading: "Revisando…", error: "No pudimos cargar esa zona. Revise el código postal e inténtelo de nuevo.", scale: "AQI de OpenWeather", updated: "Última actualización", tips: "Qué puede hacer", alerts: "Alertas meteorológicas", clear: "No hay alertas meteorológicas activas en esta zona.", levels: ["", "Bueno", "Aceptable", "Moderado", "Malo", "Muy malo"], messages: ["", "El aire está limpio para la mayoría de las personas.", "El aire es generalmente aceptable. Las personas sensibles deben observar sus síntomas.", "Las personas sensibles pueden sentir efectos del aire.", "El aire puede afectar a todos, especialmente a los grupos sensibles.", "El aire no es saludable. Reduzca la exposición tanto como sea posible."], safety: [[], ["Disfrute de sus actividades normales al aire libre.", "Abra las ventanas si las condiciones locales lo permiten."], ["Personas sensibles: descansen durante actividades largas al aire libre.", "Tenga cerca su medicamento de rescate si fue recetado."], ["Personas sensibles: reduzcan la actividad intensa al aire libre.", "Cierre las ventanas si huele humo o tiene síntomas.", "Considere una mascarilla bien ajustada afuera."], ["Limite el tiempo y el ejercicio al aire libre.", "Cierre las ventanas y use un filtro de aire si tiene uno.", "Use una mascarilla bien ajustada afuera."], ["Quédese adentro cuando sea posible.", "Use un purificador o una habitación de aire limpio.", "Siga las indicaciones locales de salud y emergencia."]] },
  hi: { name: "हिन्दी", title: "अपनी हवा जानें। स्वास्थ्य सुरक्षित रखें।", subtitle: "किसी भी अमेरिकी ज़िप कोड के लिए लाइव वायु गुणवत्ता और सरकारी मौसम चेतावनी।", zip: "अमेरिकी ज़िप कोड", placeholder: "ज़िप कोड डालें", check: "मेरा क्षेत्र देखें", loading: "जाँच हो रही है…", error: "यह क्षेत्र लोड नहीं हुआ। ज़िप कोड जाँचकर फिर कोशिश करें।", scale: "OpenWeather AQI", updated: "अंतिम अपडेट", tips: "आप क्या कर सकते हैं", alerts: "मौसम चेतावनी", clear: "इस क्षेत्र के लिए कोई सक्रिय मौसम चेतावनी नहीं है।", levels: ["", "अच्छा", "ठीक", "मध्यम", "खराब", "बहुत खराब"], messages: ["", "अधिकतर लोगों के लिए हवा साफ़ है।", "हवा सामान्यतः ठीक है। संवेदनशील लोग लक्षणों पर ध्यान दें।", "संवेदनशील लोगों पर हवा का असर हो सकता है।", "हवा सभी को, खासकर संवेदनशील लोगों को प्रभावित कर सकती है।", "हवा अस्वस्थ है। जितना हो सके संपर्क कम करें।"], safety: [[], ["सामान्य बाहरी गतिविधियाँ करें।", "स्थानीय स्थिति ठीक हो तो खिड़कियाँ खोलें।"], ["संवेदनशील लोग लंबी बाहरी गतिविधि में आराम लें।", "डॉक्टर द्वारा दी गई आपात दवा पास रखें।"], ["संवेदनशील लोग कठिन बाहरी गतिविधि कम करें।", "धुआँ या लक्षण हों तो खिड़कियाँ बंद करें।", "बाहर सही फिट वाला मास्क पहनें।"], ["बाहर समय और व्यायाम सीमित करें।", "खिड़कियाँ बंद रखें और एयर फ़िल्टर चलाएँ।", "बाहर सही फिट वाला मास्क पहनें।"], ["हो सके तो अंदर रहें।", "एयर प्यूरीफायर या साफ़ हवा वाला कमरा उपयोग करें।", "स्थानीय स्वास्थ्य और आपात निर्देश मानें।"]] },
  zh: { name: "中文", title: "了解空气，保护健康。", subtitle: "查询美国任何邮政编码的实时空气质量和官方天气警报。", zip: "美国邮政编码", placeholder: "输入邮政编码", check: "查看我的地区", loading: "正在查询…", error: "无法加载该地区。请检查邮政编码后重试。", scale: "OpenWeather 空气质量指数", updated: "最后更新", tips: "您可以这样做", alerts: "天气警报", clear: "该地区目前没有天气警报。", levels: ["", "良好", "尚可", "中等", "较差", "很差"], messages: ["", "对大多数人来说，空气很清洁。", "空气总体可以接受。敏感人群应注意症状。", "敏感人群可能会受到空气影响。", "空气可能影响所有人，尤其是敏感人群。", "空气不健康。请尽量减少接触。"], safety: [[], ["可以正常进行户外活动。", "当地条件允许时可以开窗。"], ["敏感人群长时间户外活动时应休息。", "如有处方，请随身携带急救药物。"], ["敏感人群应缩短剧烈户外活动。", "闻到烟味或出现症状时请关窗。", "外出时考虑佩戴贴合面部的口罩。"], ["限制户外时间和运动。", "关好窗户，有条件时使用空气净化器。", "外出时佩戴贴合面部的口罩。"], ["尽量留在室内。", "使用空气净化器或待在清洁空气房间。", "遵循当地卫生和应急部门的指示。"]] },
  ar: { name: "العربية", title: "اعرف هواءك. احمِ صحتك.", subtitle: "جودة الهواء المباشرة وتنبيهات الطقس الرسمية لأي رمز بريدي أمريكي.", zip: "الرمز البريدي الأمريكي", placeholder: "أدخل الرمز البريدي", check: "تحقق من منطقتي", loading: "جارٍ التحقق…", error: "تعذر تحميل هذه المنطقة. تحقق من الرمز البريدي وحاول مجددًا.", scale: "مؤشر OpenWeather", updated: "آخر تحديث", tips: "ما يمكنك فعله", alerts: "تنبيهات الطقس", clear: "لا توجد تنبيهات طقس نشطة لهذه المنطقة.", levels: ["", "جيد", "مقبول", "متوسط", "سيئ", "سيئ جدًا"], messages: ["", "الهواء نظيف لمعظم الناس.", "الهواء مقبول عمومًا. على الأشخاص الحساسين مراقبة الأعراض.", "قد يشعر الأشخاص الحساسون بتأثيرات الهواء.", "قد يؤثر الهواء على الجميع، وخاصة الفئات الحساسة.", "الهواء غير صحي. قلل التعرض قدر الإمكان."], safety: [[], ["استمتع بالأنشطة الخارجية المعتادة.", "افتح النوافذ إذا سمحت الظروف المحلية."], ["على الأشخاص الحساسين أخذ استراحات أثناء النشاط الخارجي الطويل.", "احتفظ بدواء الإنقاذ قريبًا إذا وصفه الطبيب."], ["على الأشخاص الحساسين تقليل النشاط الخارجي الشاق.", "أغلق النوافذ إذا شممت الدخان أو شعرت بأعراض.", "استخدم كمامة محكمة في الخارج."], ["قلل الوقت والتمارين في الخارج.", "أغلق النوافذ واستخدم مرشح هواء إن توفر.", "ارتدِ كمامة محكمة في الخارج."], ["ابقَ في الداخل قدر الإمكان.", "شغّل منقي الهواء أو استخدم غرفة بهواء نظيف.", "اتبع إرشادات الصحة والطوارئ المحلية."]] },
} as const;

export default function Home() {
  const [language, setLanguage] = useState<Language>("en");
  const [zip, setZip] = useState("");
  const [result, setResult] = useState<Result | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const t = copy[language];

  async function search(event: FormEvent) {
    event.preventDefault();
    if (!/^\d{5}$/.test(zip)) { setError(t.error); return; }
    setLoading(true); setError("");
    try {
      const response = await fetch(`/api/air-quality?zip=${zip}`);
      const data = await response.json();
      if (!response.ok) throw new Error(data.error);
      setResult(data);
    } catch { setResult(null); setError(t.error); }
    finally { setLoading(false); }
  }

  return <main dir={language === "ar" ? "rtl" : "ltr"}>
    <header><a href="#top" className="brand"><span aria-hidden="true">●</span> SafeSignal</a><select aria-label="Language" value={language} onChange={(event) => setLanguage(event.target.value as Language)}>{Object.entries(copy).map(([code, value]) => <option key={code} value={code}>{value.name}</option>)}</select></header>
    <section className="hero" id="top"><p className="eyebrow">LIVE AIR QUALITY · UNITED STATES</p><h1>{t.title}</h1><p className="subtitle">{t.subtitle}</p><form onSubmit={search}><label htmlFor="zip">{t.zip}</label><div className="search"><input id="zip" aria-describedby={error ? "search-error" : undefined} inputMode="numeric" pattern="[0-9]{5}" maxLength={5} value={zip} onChange={(event) => setZip(event.target.value.replace(/\D/g, ""))} placeholder={t.placeholder}/><button disabled={loading}>{loading ? t.loading : t.check}</button></div>{error && <p id="search-error" className="error" role="alert">{error}</p>}</form></section>
    {result && <section className="result" aria-live="polite"><div className="result-heading"><div><p className="eyebrow">{result.location.name} · {result.location.zip}</p><h2>{t.levels[result.aqi]}</h2><p>{t.messages[result.aqi]}</p></div><div className={`aqi-circle aqi-${result.aqi}`}><strong>{result.aqi}</strong><span>{t.scale}<br/>1–5</span></div></div><div className="detail-grid"><article><h3>{t.tips}</h3><ul>{t.safety[result.aqi].map((tip) => <li key={tip}>{tip}</li>)}</ul></article><article><h3>PM2.5</h3><p className="metric">{Math.round(result.pollutants.pm2_5 ?? 0)} <small>µg/m³</small></p><p>PM10: {Math.round(result.pollutants.pm10 ?? 0)} µg/m³</p></article></div><div className="weather"><div className="weather-title"><h3>{t.alerts}</h3><span>{result.alerts.length} ACTIVE</span></div>{result.alerts.length === 0 ? <p className="clear">✓ {t.clear}</p> : result.alerts.map((alert) => <article className="alert" key={alert.id}><small>{alert.severity}</small><h4>{alert.event}</h4><p>{alert.headline}</p></article>)}</div><p className="timestamp">{t.updated}: {new Date(result.updatedAt).toLocaleString(language)} · OpenWeatherMap · NOAA/NWS</p></section>}
    <footer><strong>SafeSignal</strong><p>For awareness only. Follow local authorities during an emergency.</p></footer>
  </main>;
}
